name: quds_mysql
description: An expansion package that simplifies creating databases and tables, crud operations, queries with modelization using mysql1
version: 1.0.1+2
homepage: https://github.com/MohammedAsaadAsaad/quds_mysql

environment:
  sdk: '>=2.14.2 <3.0.0'

dependencies: 
  mysql1: ^0.19.2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

